app/users/views.py
from crypt import methods
from functools import wraps
from flask import Blueprint, flash, render_template, redirect, url_for, session, g, request
from .forms import NewEngForm
from .models import db, create_engineer, get_eng_by_name, get_all_eng, delete_engineer
from .decorators import authenticate


module = Blueprint('users', __name__)



@module.route('/')
@authenticate
def list():
    users_list = get_all_eng()
    return render_template('users_list.html', list = users_list)


@module.route('/new', methods=['POST','GET'])
@authenticate
def new():
    form = NewEngForm()
    if form.validate_on_submit():
        if form.password.data == form.confirm_password.data:
            try:
                create_engineer(form.username.data, form.password.data, form.is_admin.data)
                return redirect(url_for('users.list'))
            except:    
                flash('Что-то пошло не так. Не удалось создать пользователя.')
        else:
            flash('Введенные пароли отличаются.')    

    return render_template('new_eng.html', form=form)  


@module.route('/delete/<user>', methods=['get'])
@authenticate
def delete_user(user):
    eng = get_eng_by_name(user)
    delete_engineer(eng)
    return redirect(url_for('users.list'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <img class="navbar-brand" src="{{ url_for('static', filename='logo.png') }}" width="189" height="60" >
    </nav>
    <div class="container">
      <div class="row">
	 <div class="col">
	 </div>
	 <div class="col-8">
      {% block content %}
	    {% endblock %}
	 </div>
	 <div class="col">
	 </div>	 
      </div>	
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/get_config.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
  <div class="row gx-5">	
    <legend class="text-center">Конфигурационные файлы для врача: {{ doctor }}</legend>
  </div>  
  <form action="" method="post">
    {{ form.csrf_token() }}
    <div class="form-group p-3 border bg-light">
      {{ form.center_name.label }}
      {{ form.center_name(class_="form-select form-select-lg mb-3") }}
	    <div class="alert alert-primary" role="alert">
  		  Если это будет первым подключением врача к данному диагностическому центру,
		    необходимо установить флаг "Зарегистрировать учетную запись врача на оборудовании ДЦ" 
	    </div>
      {{ form.create_accaunt_on_host(class_="form-check-input") }}
      {{ form.create_accaunt_on_host.label(class_="form-check-label") }}
    </div>
	  <div class="d-grid gap-2 p-3">
      {{ form.submit(class_="btn-lg btn-primary btn-block") }}
	  </div>
  </form>
  <a href = "/" class="link-secondary">К списку врачей</a>  
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
<div class="col-12">
  <h1> Список врачей</h1>
  <div class="row border bg-light">
    <div class="col-8 p-3">	  
    	
    </div>
    <div class="col-4 p-3" >
	<a href=/new class="btn btn-primary" >Новая учетная запись врача</a>
    </div>		    
  </div>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Поиск по фамилии" title="Введите фамилию">  

<table id="myTable" class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Фамилия врача</th>
      <th scope="col">Локальный адрес</th>
      <th scope="col">AETitle</th>
      <th scope="col">Файл аутентификации</th>
    </tr>
  </thead>
  <tbody>
  {% for accaunt in accaunt_list%}
    <tr>
      <td><a href=/config/{{ accaunt.name }}>{{ accaunt.family }}</a></td>
      <td>172.16.134.{{ accaunt.user_id }}</td>
      <td>{{ accaunt.aetitle }}</td>
      <td><a href=/auth/{{ accaunt.name }}>usr.cfg</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
</div>
<script>
  function myFunction() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }
  </script>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row ">
    {% with messages = get_flashed_messages() %}
        {% if messages %}     
            {% for message in messages %}
                <div class="alert alert-danger text-center">
                {{ message }}
                </div>
            {% endfor %}
        {% endif%}    
    {% endwith %}      
    <div class="col"></div>
    <div class="col-3">
        <form action="" method="post">     
            {{ form.csrf_token() }}      
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class_="form-control") }}

                {{ form.password.label }}
                {{ form.password(class_="form-control") }}
            </div>
            <div class="d-grid gap-2 p-3">
                {{ form.submit(class_="btn btn-primary") }}
            </div>    
        </form>
    </div>
    
    <div class="col"></div>
    
            
</div>
{% endblock %}

app/templates/new_accaunt.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="row gx-5">	
      <legend class="text-center">Новая учетная запись врача</legend>
    </div>  
    <form action="" method="post">
        {{ form.csrf_token() }}
        <div class="form-group border bg-light">
            {{ form.accaunt_name.label }}
            {{ form.accaunt_name(class_="form-control mb-3") }}
            {% for field, errors in form.errors.items() %}
                <small class="form-text text-danger">
                    {{ ', '.join(errors) }}
                </small>
            {% endfor %}
            <div class="alert alert-primary" role="alert">
                Если у врача уже установлено ПО для обработки DICOM изображений и
                настроен AEtitle, то укажите его в поле "AETITLE". В противном случае
                оставте поле пустыми и AETitle будет сгенерирован автоматически 
            </div>
                {{ form.aetitle.label }}
                {{ form.aetitle(class_="form-control") }}
        </div>    
        <div class="d-grid gap-2 p-3">
            {{ form.submit(class_="btn-lg btn-primary btn-block") }}
        </div>
        </form>
        <a href = "/" class="link-secondary">К списку врачей</a>
</div>
  {% endblock %}

app/templates/new_eng.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h3 class="text-center"> Новый пользователь </h3>
    <div class="col-3"></div>
    <div class="col-6">
        <form action="" method="post">
            {{ form.csrf_token() }}

            <div class="mb-3">
                {{ form.username.label }}
                {{ form.username(class_="form-control") }}
            </div>

            <div class="mb-3">        
                {{ form.password.label }}
                {{ form.password(class_="form-control") }}
            </div> 

            <div class="mb-3">    
                {{ form.confirm_password.label }}
                {{ form.confirm_password(class_="form-control") }}
            </div> 

            <div class="mb-3 form-check">  
                {{ form.is_admin(class_ = "form-check-input") }}
                {{ form.is_admin.label( class_ = "form-check-label") }}
            </div>
            
            {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for message in messages %}  
                <div class="text-danger text-center" >
                    {{ message }}
                </div>
              {% endfor %}            
            {% endif %}
            {% endwith %}

            <div class="d-grid gap-2 p-3">
                {{ form.submit(class_="btn btn-primary") }}
            </div>    
        </form>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

app/templates/users_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-12">
  <h1> Инженеры ДЦ</h1>
    <div class="row bg-light">
    	

      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Учетная запись пользователя</th>
            <th scope="col">Администрирование</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for accaunt in list%}
          <tr>
            <td>{{ accaunt.name }}</td>
            <td>{{ accaunt.is_admin }}</td>
            <td><a href="{{ url_for('users.delete_user', user=accaunt.name) }}">Удалить</a> </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}